# Generated by Django 3.2.8 on 2021-11-07 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('separator', models.CharField(choices=[(',', 'Coma'), (';', 'Semicolon')], default=',', max_length=1)),
                ('string_character', models.CharField(choices=[("'", 'Single quotes'), ('"', 'Double quotes')], default="'", max_length=1)),
                ('modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('UD', 'Undefined'), ('FN', 'Full Name'), ('JB', 'Job'), ('EM', 'Email'), ('DN', 'Domain name'), ('PN', 'Phone number'), ('CN', 'Company name')], default='UD', max_length=2)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
    ]
