# Generated by Django 3.2.8 on 2021-10-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='column',
            name='schema',
        ),
        migrations.AddField(
            model_name='schema',
            name='column',
            field=models.ManyToManyField(blank=True, null=True, to='schemas.Column'),
        ),
    ]
