# Generated by Django 3.2.8 on 2021-11-03 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schema',
            name='column',
        ),
        migrations.AddField(
            model_name='column',
            name='schema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schemas.schema'),
        ),
    ]
