# Generated by Django 3.2.8 on 2021-10-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0002_auto_20211031_0135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyname',
            name='column',
        ),
        migrations.AddField(
            model_name='companyname',
            name='column',
            field=models.ManyToManyField(blank=True, to='schemas.Column'),
        ),
        migrations.RemoveField(
            model_name='domainname',
            name='column',
        ),
        migrations.AddField(
            model_name='domainname',
            name='column',
            field=models.ManyToManyField(blank=True, to='schemas.Column'),
        ),
        migrations.RemoveField(
            model_name='email',
            name='column',
        ),
        migrations.AddField(
            model_name='email',
            name='column',
            field=models.ManyToManyField(blank=True, to='schemas.Column'),
        ),
        migrations.RemoveField(
            model_name='fullname',
            name='column',
        ),
        migrations.AddField(
            model_name='fullname',
            name='column',
            field=models.ManyToManyField(blank=True, to='schemas.Column'),
        ),
        migrations.RemoveField(
            model_name='job',
            name='column',
        ),
        migrations.AddField(
            model_name='job',
            name='column',
            field=models.ManyToManyField(blank=True, to='schemas.Column'),
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='column',
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='column',
            field=models.ManyToManyField(blank=True, to='schemas.Column'),
        ),
    ]
