# Generated by Django 3.2.8 on 2021-10-31 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20211031_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyname',
            name='column',
        ),
        migrations.RemoveField(
            model_name='domainname',
            name='column',
        ),
        migrations.RemoveField(
            model_name='email',
            name='column',
        ),
        migrations.RemoveField(
            model_name='fullname',
            name='column',
        ),
        migrations.RemoveField(
            model_name='job',
            name='column',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='column',
        ),
        migrations.AddField(
            model_name='column',
            name='domain_name',
            field=models.ManyToManyField(blank=True, to='schemas.DomainName'),
        ),
        migrations.AddField(
            model_name='column',
            name='email',
            field=models.ManyToManyField(blank=True, to='schemas.Email'),
        ),
        migrations.AddField(
            model_name='column',
            name='full_name',
            field=models.ManyToManyField(blank=True, to='schemas.FullName'),
        ),
        migrations.AddField(
            model_name='column',
            name='job',
            field=models.ManyToManyField(blank=True, to='schemas.Job'),
        ),
        migrations.AddField(
            model_name='column',
            name='phone_number',
            field=models.ManyToManyField(blank=True, to='schemas.PhoneNumber'),
        ),
    ]
