# Generated by Django 3.2.8 on 2021-10-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_auto_20211031_0207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdditionalFields',
        ),
        migrations.RemoveField(
            model_name='column',
            name='domain_name',
        ),
        migrations.RemoveField(
            model_name='column',
            name='email',
        ),
        migrations.RemoveField(
            model_name='column',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='column',
            name='job',
        ),
        migrations.RemoveField(
            model_name='column',
            name='phone_number',
        ),
        migrations.DeleteModel(
            name='CompanyName',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='column',
        ),
        migrations.DeleteModel(
            name='Column',
        ),
        migrations.DeleteModel(
            name='DomainName',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='FullName',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='Schema',
        ),
    ]
