# Generated by Django 3.2.8 on 2021-10-31 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schemas', '0005_auto_20211031_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field_type', models.CharField(choices=[('UD', 'Undefined'), ('FN', 'Full Name'), ('JB', 'Job'), ('EM', 'Email'), ('DN', 'Domain name'), ('PN', 'Phone_number')], default='UD', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('separator', models.CharField(choices=[(',', 'Coma'), (';', 'Semicolon')], default=',', max_length=1)),
                ('string_character', models.CharField(choices=[('"', 'Single quotes'), ("'", 'Double quotes')], default='"', max_length=1)),
                ('column', models.ManyToManyField(blank=True, to='schemas.Column')),
            ],
        ),
    ]
