# Generated by Django 3.2.8 on 2021-10-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_column_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
