# Generated by Django 3.2.8 on 2021-10-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_column_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='field_type',
            field=models.CharField(choices=[('UD', 'Undefined'), ('FN', 'Full Name'), ('JB', 'Job'), ('EM', 'Email'), ('DN', 'Domain name'), ('PN', 'Phone number'), ('CN', 'Company name')], default='UD', max_length=2),
        ),
    ]
